import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mercuria Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Deserunt reprehenderit cupidatat irure officia fugiat magna veniam dolore eiusmod exercitation cillum incididunt irure. Ipsum irure fugiat quis mollit minim occaecat minim culpa in. Minim nulla qui Lorem irure nostrud et deserunt. Quis non mollit Lorem proident nostrud occaecat reprehenderit officia. Quis fugiat esse in sunt nisi.
          </p>
          <form action="/send-data-here" method="post">
            <label for="imo">IMO:</label>
            <input
            type="text"
            id="imo"
            name="imo"
            required
            pattern="^[0-9]{7}"
            title="Please match IMO format (7-digit number), e.g. 1234567"
            />
            <label for="long">Long:</label>
            <input
              type="text"
              id="long"
              name="long"
              pattern="\d+.\d+"
              title="Please provide in decimal degrees, e.g. 5.1254"
              required />
            <label for="lat">Lat:</label>
            <input
              type="text"
              id="lat"
              name="lat"
              pattern="\d+.\d+"
              title="Please provide in decimal degrees, e.g. 5.1254"
              required />
            <button type="submit">Submit</button>
          </form>
        </div>
      </main>
    </>
  )
}
